# Generated by Django 3.2.12 on 2024-10-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_globalapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalapikey',
            name='key',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
