# Generated by Django 3.2.12 on 2024-10-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_globalapikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalapikey',
            name='key',
            field=models.CharField(editable=False, max_length=256, unique=True),
        ),
    ]
