# Generated by Django 3.2.12 on 2024-10-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_globalapikey_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalapikey',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
