# Generated by Django 3.2.12 on 2024-10-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='count',
            field=models.IntegerField(default=1000),
        ),
    ]
