# Generated by Django 3.2.12 on 2024-10-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_client_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='uuid',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='count',
            field=models.IntegerField(),
        ),
    ]
