# Generated by Django 3.2.12 on 2024-10-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_auto_20241016_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='nom',
            new_name='email',
        ),
    ]
